services:
  web:
    build: .
    container_name: docker-devops
    ports:
      - "8000:8000"
    depends_on:
      - db
#    volumes:
#      - ./static:/app/static
    command: >
      sh -c "
        python manage.py collectstatic --noinput
        python manage.py migrate --noinput
        python -m gunicorn --bind 0.0.0.0:8000 --workers 3 your_quality_programmer.wsgi:application
      "
    volumes:
      - ./your_quality_programmer:/app
      - static_volume:/app/static
    develop:
      watch:
        - action: sync
          path: ./your_quality_programmer
          target: /app
    env_file:
      - .env
  nginx:
    image: nginx:stable
    container_name: docker-devops-proxy
    volumes:
      - static_volume:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    entrypoint: /bin/sh
  db:
    image: postgres:17
    container_name: docker-devops-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  certbot-etc:
  certbot-var:

networks:
  inside-network:
    driver: bridge