services:
  app:
    build: ./your_quality_programmer
    restart: unless-stopped
    container_name: Docker-secured
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "
      python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./your_quality_programmer:/code
    develop:
      watch:
        - action: sync
          path: ./your_quality_programmer
          target: /code
          ignore:
            - Dockerfile
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: Docker-secured-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  inside-network:
    driver: bridge