services:
  web:
    build: .
    container_name: docker-devops
    environment:
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py runserver 0.0.0.0:8000
      "
    #      sh -c "
    #        python manage.py collectstatic --noinput
    #        python manage.py migrate --noinput
    #        python -m gunicorn --bind 0.0.0.0:8000 --workers 3 your_quality_programmer.wsgi:application
    #      "
    volumes:
      - ./your_quality_programmer:/app
      - web_static:/app/static
    develop:
      watch:
        - action: sync
          path: ./your_quality_programmer
          target: /app
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: docker-devops-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
#      - ./database/postgres_data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
#  nginx:
#    build: ./nginx
#    container_name: docker-devops-proxy
#    volumes:
#      - web_static:/static:ro
#      - static:/var/www/certbot
#      - certbot_www:/var/www/certbot
#      - certbot_etc:/etc/letsencrypt
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - web
#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - certbot_www:/var/www/certbot
#      - certbot_etc:/etc/letsencrypt
#    command: certonly --webroot -w /var/www/certbot --force-renewal --email yourqualityprogrammer@gmail.com -d yourhonestprogrammer.com --agree-tos

volumes:
  postgres_data:
  web_static:
  certbot_www:
  certbot_etc:

networks:
  inside-network:
    driver: bridge