services:
  django-web:
    build: .
    container_name: docker-devops
    depends_on:
      - db
    command: >
      sh -c "
        tail -f /dev/null
      "
    env_file:
      - .env
#  app:
#    build: .
#    restart: unless-stopped
#    container_name: docker-secured
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    command: >
#      sh -c "
#        tail -f /dev/null
#      "
#    volumes:
#      - ./your_quality_programmer:/app
#    develop:
#      watch:
#        - action: sync
#          path: ./your_quality_programmer
#          target: /app
#          ignore:
#            - Dockerfile
#    env_file:
#      - .env
  db:
    image: postgres:17
    container_name: docker-devops-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  inside-network:
    driver: bridge